name: Deploy Frontend

# Se activará cuando detecte cambios en los archivos dentro del front-end
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'front/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Descargar código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

    # Configurar inicial de Node.js
      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

    # Ejecuta los archivos para levantar el front-end
      - name: Build frontend
        run: |
          cd front
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Synchronize files to S3
        run: aws s3 sync front/dist/ s3://sachatrace-dev-front --delete