name: Deploy Frontend

# Se activará cuando detecte cambios en los archivos dentro del front-end
on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'front/**'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    # Descargar código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

    # Configurar inicial de Node.js
      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

    # Ejecuta los archivos para levantar el front-end
      - name: Build frontend
        run: |
          cd front
          npm install
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: front/dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    # Sube el artefacto generado
      - name: Synchronize files to S3 dev
        run: aws s3 sync front/dist/ s3://mallkitrace-dev-front --delete

    # Invalidar caché de CloudFront para un despliegue inmediato
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' && success()

    steps:
      # Descarga el artefacto generado
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: front/dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_USER_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Configura credenciales AWS para prod
      - name: Synchronize files to S3 prod
        run: aws s3 sync front/dist/ s3://sachatrace-front --delete 

      # Invalidar caché de CloudFront para un despliegue inmediato
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"
